version: "3"

services:
    node:
        image: node:14.0.0-alpine3.11
        user: node
        tty: true
        stdin_open: true
        working_dir: /home/node
        volumes:
            - .:/home/node
