"use strict";

class Rule {
    /**
     * Instanciate a new rule.
     *
     * @param {{attributeName: string, attributes: Record<string, any>, ruleName: string, translations: Record<string, Record<string, string>>}} options
     *
     * @return {Rule}
     *
     * @example
     * const rule = new Rule({"username", {username: "johndoe"}, "required", {username: {required: "The username is required"}}});
     */
    constructor({attributeName, attributes, ruleName, translations}) {
        this.attributeName = attributeName;
        this.attributeVale = attributes[attributeName];
        this.attributes = attributes;
        this.translations = translations;
        this.ruleName = ruleName.trim();
        this.ruleValue = null;
        this.error = null;
    }

    /**
     * Check if a given rule match the rule.
     *
     * @param {string} rule
     *
     * @return {boolean}
     *
     * @example
     * rule.match("required");
     * rule.match("same:password");
     */
    match(rule) {
        const [ruleName, ruleValue] = rule.split(":");

        if (this.ruleName === ruleName) {
            if ("undefined" !== typeof ruleValue) {
                this.ruleValue = ruleValue.trim();
            }

            return true;
        }

        return false;
    }

    /**
     * Check if the rule has a validation error.
     *
     * @return {boolean}
     *
     * @example
     * rule.hasError();
     */
    hasError() {
        this.validate();

        return null !== this.error;
    }

    /**
     * Return the error generated by the rule.
     *
     * @return {string}
     *
     * @example
     *
     * rule.getError(); // "The username is required."
     */
    getError() {
        const {error, translations, attributeName, ruleName} = this;

        if (null !== error && "undefined" !== typeof translations[this.attributeName] && "undefined" !== typeof translations[attributeName][ruleName]) {
            return translations[attributeName][ruleName];
        }

        return error;
    }
}

exports.Rule = Rule;
